# theme: jekll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
title: Cloudflare Warp GUI
description: A Python GUI originally made just for Linux users to use Cloudflare WARP using a GUI since Linux only had a CLI
show_downloads: true
github:
  zip_url: https://github.com/DNAMcKnight/CloudflareWarpGUI/releases
  another_url: https://github.com/DNAMcKnight/CloudflareWarpGUI/releases
  tar_url: https://github.com/DNAMcKnight/CloudflareWarpGUI/releases
